/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HDF5CREAT_H_RPCGEN
#define _HDF5CREAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define HDF5SERVER 0x2fffffff
#define HDF5SERVER_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define creat_file 1
extern  int * creat_file_1(char **, CLIENT *);
extern  int * creat_file_1_svc(char **, struct svc_req *);
extern int hdf5server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define creat_file 1
extern  int * creat_file_1();
extern  int * creat_file_1_svc();
extern int hdf5server_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HDF5CREAT_H_RPCGEN */
